### ISSUE TITLE
Débugger la machine

### ISSUE THREAD

**Issue by plaurin84** [ClubCedille/nETSpresso#3]
La machine se déconnecte d'elle-même chez Critias, il faut s'organiser pour qu'elle fonctionne comme prévu.

**Comment by samdidos** [comment]
Après plusieurs checkups, il semblerait que ce soit la connexion PoE qui fait défaut. La machine a très bien fonctionné durant notre démonstration du 24 novembre 2015 à l'inauguration de Star ÉTS.

**Comment by gzsierra** [comment]
Problème de port mal déclaré dans le code.
Solution : mettre une variable local dans l'arduino
